# Generated by Django 3.1 on 2022-07-26 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=250)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('course_fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('course_overview', models.TextField(max_length=2000)),
                ('course_deteil', models.CharField(max_length=250)),
                ('course_intro', models.CharField(max_length=250)),
                ('resources', models.CharField(max_length=250)),
                ('learning_outcomes', models.CharField(max_length=250)),
            ],
        ),
    ]
