# Generated by Django 3.1 on 2022-08-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnApp', '0003_auto_20220729_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='images/infot.jpg', upload_to='images'),
        ),
    ]
