# Generated by Django 3.1 on 2022-08-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnApp', '0004_auto_20220818_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
